{% set name = "svt-av1" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v{{ version }}/SVT-AV1-v{{ version }}.tar.gz
  sha256: 3999586c261dc3d8690fd1489fc74da4e0fdff9159c8ce2b76ddfac001ad96d3

build:
  number: 0
  run_exports:
    # This is just a guess
    - {{ pin_subpackage('svt-av1', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - yasm

test:
  commands:
    - test -f $PREFIX/include/svt-av1/EbSvtAv1.h     # [unix]
    - test -f $PREFIX/lib/libSvtAv1Enc${SHLIB_EXT}   # [unix]
    - SvtAv1EncApp --help  # [unix and build_platform == target_platform]

about:
  home: https://gitlab.com/AOMediaCodec/SVT-AV1
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The Scalable Video Technology for AV1 encoder/decoder library.
  description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder) is an
    AV1-compliant encoder/decoder library core.

extra:
  recipe-maintainers:
    - matthiasdiener
