{% set name = "svt-av1" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v{{ version }}/SVT-AV1-v{{ version }}.tar.gz
  sha256: 9c0f9a4327334c40a76d2f39940d8a1b2dd8b1358375a11c4715d516b90a65cb

build:
  number: 0
  run_exports:
    # This is just a guess
    - {{ pin_subpackage('svt-av1', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - yasm

test:
  commands:
    - test -f $PREFIX/include/svt-av1/EbSvtAv1.h     # [unix]
    - test -f $PREFIX/lib/libSvtAv1Enc${SHLIB_EXT}   # [unix]
    - SvtAv1EncApp --help  # [unix and build_platform == target_platform]

about:
  home: https://gitlab.com/AOMediaCodec/SVT-AV1
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The Scalable Video Technology for AV1 encoder/decoder library.
  description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder) is an
    AV1-compliant encoder/decoder library core.

extra:
  recipe-maintainers:
    - matthiasdiener
