{% set name = "svt-av1" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v{{ version }}/SVT-AV1-v{{ version }}.tar.gz
  sha256: 51a41fc38ced0e9a56aa4300b1d872f3b43e2421644110852dfdb67440080c63

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - yasm

test:
  commands:
    - test -f $PREFIX/include/svt-av1/EbSvtAv1.h     # [unix]
    - test -f $PREFIX/lib/libSvtAv1Dec${SHLIB_EXT}   # [unix]
    - test -f $PREFIX/lib/libSvtAv1Enc${SHLIB_EXT}   # [unix]
    - SvtAv1EncApp --help  # [build_platform == target_platform]
    - SvtAv1DecApp --help  # [build_platform == target_platform]

about:
  home: https://gitlab.com/AOMediaCodec/SVT-AV1
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The Scalable Video Technology for AV1 encoder/decoder library.
  description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder) is an
    AV1-compliant encoder/decoder library core.

extra:
  recipe-maintainers:
    - matthiasdiener
